import { z } from "zod";
export declare const addItemSchema: z.ZodObject<{
    name: z.ZodString;
    content: z.ZodString;
    sourceId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    name?: string;
    sourceId?: string;
    content?: string;
}, {
    name?: string;
    sourceId?: string;
    content?: string;
}>;
export declare const webhookBodySchema: z.ZodObject<{
    type: z.ZodOptional<z.ZodString>;
    userId: z.ZodOptional<z.ZodString>;
    sec_uid: z.ZodOptional<z.ZodString>;
    authorId: z.ZodOptional<z.ZodString>;
    userName: z.ZodOptional<z.ZodString>;
    text: z.ZodOptional<z.ZodString>;
    message: z.ZodOptional<z.ZodString>;
    commentId: z.ZodOptional<z.ZodString>;
    messageId: z.ZodOptional<z.ZodString>;
    video_id: z.ZodOptional<z.ZodString>;
    item_id: z.ZodOptional<z.ZodString>;
    post_id: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    caption: z.ZodOptional<z.ZodString>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    type: z.ZodOptional<z.ZodString>;
    userId: z.ZodOptional<z.ZodString>;
    sec_uid: z.ZodOptional<z.ZodString>;
    authorId: z.ZodOptional<z.ZodString>;
    userName: z.ZodOptional<z.ZodString>;
    text: z.ZodOptional<z.ZodString>;
    message: z.ZodOptional<z.ZodString>;
    commentId: z.ZodOptional<z.ZodString>;
    messageId: z.ZodOptional<z.ZodString>;
    video_id: z.ZodOptional<z.ZodString>;
    item_id: z.ZodOptional<z.ZodString>;
    post_id: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    caption: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    type: z.ZodOptional<z.ZodString>;
    userId: z.ZodOptional<z.ZodString>;
    sec_uid: z.ZodOptional<z.ZodString>;
    authorId: z.ZodOptional<z.ZodString>;
    userName: z.ZodOptional<z.ZodString>;
    text: z.ZodOptional<z.ZodString>;
    message: z.ZodOptional<z.ZodString>;
    commentId: z.ZodOptional<z.ZodString>;
    messageId: z.ZodOptional<z.ZodString>;
    video_id: z.ZodOptional<z.ZodString>;
    item_id: z.ZodOptional<z.ZodString>;
    post_id: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    caption: z.ZodOptional<z.ZodString>;
}, z.ZodTypeAny, "passthrough">>;
export declare const aiSettingsSchema: z.ZodObject<{
    coachProvider: z.ZodEnum<["openai", "gemini", "openrouter", "groq"]>;
    coachModel: z.ZodString;
    customerProvider: z.ZodEnum<["openai", "gemini", "openrouter", "groq"]>;
    customerModel: z.ZodString;
    openaiApiKey: z.ZodOptional<z.ZodString>;
    openaiModel: z.ZodString;
    openaiEmbeddingModel: z.ZodString;
    geminiApiKey: z.ZodOptional<z.ZodString>;
    geminiModel: z.ZodString;
    openrouterApiKey: z.ZodOptional<z.ZodString>;
    openrouterModel: z.ZodString;
    groqApiKey: z.ZodOptional<z.ZodString>;
    groqModel: z.ZodString;
    temperature: z.ZodEffects<z.ZodString, string, string>;
    maxTokens: z.ZodNumber;
    topP: z.ZodEffects<z.ZodString, string, string>;
    systemPromptTemplate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    rateLimitPerMinute: z.ZodNumber;
    retryAttempts: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    coachProvider?: "openai" | "gemini" | "openrouter" | "groq";
    coachModel?: string;
    customerProvider?: "openai" | "gemini" | "openrouter" | "groq";
    customerModel?: string;
    openaiApiKey?: string;
    openaiModel?: string;
    openaiEmbeddingModel?: string;
    geminiApiKey?: string;
    geminiModel?: string;
    openrouterApiKey?: string;
    openrouterModel?: string;
    groqApiKey?: string;
    groqModel?: string;
    temperature?: string;
    maxTokens?: number;
    topP?: string;
    systemPromptTemplate?: string;
    rateLimitPerMinute?: number;
    retryAttempts?: number;
}, {
    coachProvider?: "openai" | "gemini" | "openrouter" | "groq";
    coachModel?: string;
    customerProvider?: "openai" | "gemini" | "openrouter" | "groq";
    customerModel?: string;
    openaiApiKey?: string;
    openaiModel?: string;
    openaiEmbeddingModel?: string;
    geminiApiKey?: string;
    geminiModel?: string;
    openrouterApiKey?: string;
    openrouterModel?: string;
    groqApiKey?: string;
    groqModel?: string;
    temperature?: string;
    maxTokens?: number;
    topP?: string;
    systemPromptTemplate?: string;
    rateLimitPerMinute?: number;
    retryAttempts?: number;
}>;
//# sourceMappingURL=validation.d.ts.map